### ISSUE TITLE
3d depth subtitle

### ISSUE THREAD

**Issue by juneleung** [cth103/dcpomatic#17]
can it work with 3d subtitle by import 3d xml+png or 3d xml+font? 
seems to lose Zposition in sub xml after being packaged .

**Comment by cth103** [comment]
You're right.  I added this to the main bug tracker here: https://dcpomatic.com/bugs/view.php?id=2356 and I'll fix it as soon as I can.

**Comment by juneleung** [comment]
Thanks for your great work!!
:)




---- Replied Message ----
| From | Carl ***@***.***> |
| Date | 10/21/2022 06:35 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [cth103/dcpomatic] 3d depth subtitle (Issue #17) |

You're right. I added this to the main bug tracker here: https://dcpomatic.com/bugs/view.php?id=2356 and I'll fix it as soon as I can.

**Comment by UltraBlur** [comment]
"I'm sorry, when I try to create a 3D DCP with XML+PNG, it seems that the Z-position is still lost. I am using version 2.16.66."

**Comment by UltraBlur** [comment]
I'm sorry, when I try to create a 3D DCP with XML+PNG, it seems that the Z-position is still lost. I am using version 2.16.66.

**Comment by cth103** [comment]
Thanks for the note, I'll take another look (I re-opened the bug on the main tracker)
