### ISSUE TITLE
Build errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by PeterTaps** [cth103/dcpomatic#2]
I followed the build instructions from:

https://dcpomatic.com/build/linux?distro=ubuntu-18.04

However, when building dcp-o-matic, I am seeing the following error:

../src/lib/dcp_examiner.cc: In constructor ‘DCPExaminer::DCPExaminer(boost::shared_ptr<const DCPContent>)’:
../src/lib/dcp_examiner.cc:138:18: error: no match for ‘operator+=’ (operand types are ‘Frame {aka long int}’ and ‘boost::optional<long int>’)

Does anyone know how to fix this?

Thanks
Peter

**Comment by cth103** [comment]
Sorry, you will need to be on the v1.6.x branch of libdcp to build DCP-o-matic master at the moment.  Go into your libdcp directory, do 

git checkout v1.6.x

then re-build/install libdcp and try again.
