### ISSUE TITLE
An error when reading a KDM

### ISSUE THREAD

**Issue by wunderbarb** [cth103/dcpomatic#20]
Using `dcpomatic2_create` with version 2.16.62
I get the following error `dcpomatic2_create: Programming error at ../src/utc_offset.cc:53`
The KDM was generated for a `dcpomatic2` private key using `<!-- Generated by Key Store Plugin (Waimea) v0.6.52 (wlib 3.3.15) -->`

Of course, the same error occurs when using GUI `dcpomatic2` and `dcpomatic2_player`.

What may produce such an error?

PS: I tested on two different KDMs for two DCPs produced by the same provider.  It triggered the the same error.

**Comment by cth103** [comment]
Hello, can you attach the KDM, or email it to carl@dcpomatic.com ?

**Comment by wunderbarb** [comment]
I will send it by email. Thanks

**Comment by cth103** [comment]
Thanks for the KDM.  Hopefully this should be fixed by c505a48de5f77c35865fe2676af10d36830cc9ba which will end up in a release soon-ish.  Let me know if this is urgent for you and I'll make a release more quickly.

**Comment by wunderbarb** [comment]
Thanks Carl.  Unfortunately, it is rather urgent.

**Comment by cth103** [comment]
Fair enough, 2.16.64 should fix this and will be uploaded [here](https://dcpomatic.com/download/2.16.64), hopefully within the next 12-18 hours.

**Comment by wunderbarb** [comment]
The KDM was working properly with this version.  Thanks.

**Comment by cth103** [comment]
Thanks for reporting back!
