### ISSUE TITLE
Importing SMPTE 2014 XML with Ruby Element for Japanese subtitles does not work

### ISSUE THREAD

**Issue by UltraBlur** [cth103/dcpomatic#23]
I am trying to create a subtitle with Ruby Element (furigana annotation) for Japanese subtitles. I manually modified the SMPTE 2014 XML created by Subtitle Edit, but when I try to import it in O-Matic, it gives me an error. O-Matic seems to not recognize Ruby (unexpected node Ruby). Is this a bug or a missing feature in the software?

**Comment by cth103** [comment]
They're just not handled right now, unfortunately. I [made a note](https://dcpomatic.com/bugs/view.php?id=2635) in the main bugtracker to look into it.

**Comment by cth103** [comment]
7a877ff976b119a39797c1f6e8477b92dfbb30ca adds passthrough of Ruby elements; it should work in 2.16.67 when that is uploaded. Let me know if you have problems there!
