### ISSUE TITLE
build errors invalid conversion boost::optional<TYPE> -> TYPE (macOS)

### ISSUE THREAD

**Issue by tschiemer** [cth103/dcpomatic#3]
Trying to build dcpomatic  there is a large amount of errors that essentially just state that 

```
../src/lib/dcp_decoder.cc:173:17: error: no viable conversion from 'boost::optional<int64_t>' (aka 'optional<long long>') to 'const int64_t' (aka 'const long long')
                int64_t const entry_point = (*_reel)->main_sound()->entry_point ();
```

This is one of many identical errors.

Can be resolved with dereferencing.. ie `*( XY )`.

I don't know if this is a particular platform error maybe?
I had to fix up the configuration step a bit to make it work on my system..

Or am I not using the latest version?

**Comment by cth103** [comment]
If you are building DCP-o-matic master you need the v1.6.x branch of libdcp at the moment.

**Comment by tschiemer** [comment]
ah I see, I was using the latest branch from https://github.com/cth103/libdcp/ instead of http://main.carlh.net/gitweb/?p=libdcp.git;a=summary

I'll have a look at it next week, I think

**Comment by cth103** [comment]
I've pushed that branch of libdcp to github now.  Sorry about that!

**Comment by tschiemer** [comment]
ok many thanks!

may I ask, I had dcpomatic branch 2.15 (accidently but successfully..) compile against the libdcp master, but not against libdcp 1.6 (it's missing the Rating class, at least).

so just to make sure I have the versions right: dcpomatic 2.15 (or master?) should compile against libdcp 1.6?

**Comment by cth103** [comment]
v2.15.x dcpomatic -> libdcp master
master dcpomatic -> libdcp v1.6.x

I know it's a bit confusing.  v2.15.x dcpomatic will become master at some point fairly soon.
