### ISSUE TITLE
libdcpomatic2.so: undefined symbol

### ISSUE THREAD

**Issue by acidhell** [cth103/dcpomatic#5]
dcpomatic2: symbol lookup error: /usr/local/lib64/libdcpomatic2.so: undefined symbol: _ZN4cxml11raw_convertIiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEET_T0_

**Comment by cth103** [comment]
Hey, sorry, I only just saw this.  What are you building on?

**Comment by cah-ableton** [comment]
ping @acidhell
