### ISSUE TITLE
dcpomatic2_create cli --standard interop does not set it to interop

### ISSUE THREAD

**Issue by candreacchio** [cth103/dcpomatic#9]
Hi there,

Trying to automate a few tasks on our end... adding the argument --standard interop, then viewing the resultant dcp in dcpomatic shows that the interop is not being set correctly. Manually changing the <interop>0</interop> to <interop>1</interop> in the xml file seems to fix this.

command to test is as follows:

dcpomatic2_create -n 'test' --standard interop -o ~/testDCP/ '/mnt/xxxx/xxxx/xxxxx/xxxxx.wav' --content-ratio 239

dcpomatic2 version 2.14.37 git d1e9749ca2

**Comment by cth103** [comment]
Thanks for letting me know - that should be fixed by c1e8c8638bcb3b4c9d90adc3719f38fa7bf81be9 and I'll make 2.14.38 in the next few hours.

**Comment by cth103** [comment]
2.14.38 is up now - let me know if you have the same problem there! :+1:
